name: youthapp
description: Youth Mobile App for Equity Lab Platform

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.3
  form_field_validator: ^1.0.1
  json_annotation: ^4.1.0
  url_launcher: ^6.0.10
  open_mail_app: ^0.3.0
  flutter_secure_storage: ^4.2.1
  jwt_decoder: ^2.0.1
  flutter_login_facebook: ^1.1.0
  carousel_slider: ^4.0.0
  animated_splash_screen: ^1.1.0
  image_picker: ^0.8.4+2
  material_floating_search_bar: ^0.3.4
  flutter_svg: ^0.22.0
  flutter_signin_button: ^2.0.0
  responsive_framework: ^0.1.4
  loadmore: ^2.0.1
  http_interceptor: ^1.0.2
  flutter_rating_bar: ^4.0.0
  toggle_switch: ^1.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2


dependency_overrides:
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  json_serializable: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: fonts/SFProDisplay-Regular.ttf
          weight: 700
    - family: Nunito
      fonts:
        - asset: fonts/Nunito/Nunito-Black.ttf
          weight: 900
        - asset: fonts/Nunito/Nunito-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: fonts/Nunito/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: fonts/Nunito/Nunito-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: fonts/Nunito/Nunito-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Nunito/Nunito-Regular.ttf
        - asset: fonts/Nunito/Nunito-Italic.ttf
          style: italic
        - asset: fonts/Nunito/Nunito-Light.ttf
          weight: 300
        - asset: fonts/Nunito/Nunito-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: fonts/Nunito/Nunito-SemiBoldItalic.ttf
          weight: 600
          style: italic
    - family: Rubik
      fonts:
        - asset: fonts/Rubik/Rubik-Black.ttf
          weight: 900
        - asset: fonts/Rubik/Rubik-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Rubik/Rubik-Bold.ttf
          weight: 700
        - asset: fonts/Rubik/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: fonts/Rubik/Rubik-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Rubik/Rubik-Regular.ttf
        - asset: fonts/Rubik/Rubik-Italic.ttf
          style: italic
        - asset: fonts/Rubik/Rubik-Light.ttf
          weight: 300
        - asset: fonts/Rubik/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: fonts/Rubik/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: fonts/Rubik/Rubik-SemiBoldItalic.ttf
          weight: 600
          style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
